name: Automated tests

on:
  workflow_dispatch:
    inputs:
      base_url:
        description: 'Base URL for tests'
        required: true
        default: 'demo'
      path:
        description: 'Path for tests'
        required: true
        default: '149551799240'
      browser_name:
        description: 'Browser for tests chrome or firefox'
        required: true
        default: 'chrome'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11.5"
      - name: Install Chrome
        run: sudo apt-get install google-chrome-stable
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Run tests
        run: pytest -s -v --base_url=${{ github.event.inputs.base_url }} --path=${{ github.event.inputs.path }} --browser_name=${{ github.event.inputs.browser_name }}
